default: &default
  adapter: postgis
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: datewari_development

test:
  <<: *default
  database: datewari_test
  <% if ENV['CI'] %>
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>

production:
  <<: *default
  database: datewari_production
